name: chabo
description: Mobile app to get the closing and opening schedules of the Chaban Delmas bridge located in Bordeaux, France

publish_to: 'none'

version: 0.5.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  enum_to_string: ^2.0.1
  file: ^6.1.4 # Prevent build errors (https://stackoverflow.com/questions/73561012/flutter-the-method-file-create-has-fewer-named-arguments-than-those-of-overrid)
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_markdown: ^0.6.14
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.0
  http: ^0.13.0
  intl: ^0.17.0
  package_info_plus: ^3.0.3
  shared_preferences: ^2.0.17
  stream_transform: ^2.0.0
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/chabo_icon.png
    - CHANGELOG.md

flutter_icons:
  android: true
  ios: false
  remove_alpha_ios: false
  image_path: assets/images/chabo_icon.png
  adaptive_icon_foreground: assets/images/chabo_icon.png
  adaptive_icon_background: "#FFFFFF"


