name: chabo
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_bloc: ^8.0.0
  http: ^0.13.0
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  intl: ^0.18.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  generate: true
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: assets/images/chabo_icon.png
  image_path_android: assets/images/chabo_icon.png

