name: chabo
description: Mobile app to get the closing and opening schedules of the Chaban Delmas bridge located in Bordeaux, France

publish_to: 'none'

version: 1.9.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '3.10.0'

dependencies:
  animated_toggle_switch: ^0.6.2
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^14.0.0
  flutter_markdown: ^0.6.14
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.0
  google_mobile_ads: ^3.0.0
  http: ^0.13.0
  intl: ^0.18.0
  package_info_plus: ^4.0.0
  shared_preferences: ^2.0.17
  stream_transform: ^2.0.0
  timezone: ^0.9.1
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
  dart_code_metrics: ^5.7.3
  bloc_test: ^9.1.1
  mockito: ^5.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/chabo_icon.png
    - CHANGELOG_en.md
    - CHANGELOG_fr.md
    - CHANGELOG_es.md

flutter_icons:
  android: true
  ios: false
  remove_alpha_ios: false
  image_path: assets/images/chabo_icon.png
  adaptive_icon_foreground: assets/images/chabo_icon.png
  adaptive_icon_background: "#FFFFFF"


